### ISSUE TITLE
bug auto dongeon

### ISSUE THREAD

**Issue by XenoRay2205** [lordkyuusei/pokeclicker-companion#1]
J'ai un bug lorsque que j'essaye de lancer l'auto complétion des donjons.

Je suis sous opéra GX avec la version de l'ext 1.2.7, et quand je lance la fonctionnalité le donjon se lance mais aucune action ne se passe

**Comment by lordkyuusei** [comment]
désolé du délai! j'ai totalement délaissé le projet quand la hype est retombée ; c'est sans doute lié à la mise à jour du jeu qui a incorporé les étages avec Galar. J'essaye de voir ce que je peux faire !

EDIT: problème réglé, voir les releases ou la page chrome/edge de l'extension :)
